name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      # - name: Run Tests (Backend)
      #   working-directory: ./backend
      #   run: npm test

      # - name: Lint Code (Backend)
      #   working-directory: ./backend
      #   run: npm run lint

      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      # - name: Run Tests (Frontend)
      #   working-directory: ./frontend
      #   run: npm test

      # - name: Lint Code (Frontend)
      #   working-directory: ./frontend
      #   run: npm run lint

  build_and_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        working-directory: ./backend
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t userwei/nycu_service-learning-nanao:backend-$IMAGE_TAG .
          docker push userwei/nycu_service-learning-nanao:backend-$IMAGE_TAG

      - name: Build and Push Frontend Image
        working-directory: ./frontend
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t userwei/nycu_service-learning-nanao:frontend-$IMAGE_TAG .
          docker push userwei/nycu_service-learning-nanao:frontend-$IMAGE_TAG

      # - name: SSH and Deploy
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /path/to/your/deployment
      #       git pull origin main
      #       docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      #       docker-compose pull
      #       docker-compose up -d --remove-orphans
